export const data  = {
  "iconLink": "agency_icons/minopex.png",
  "title": "minopex",
  "blogPosts": [
    {
      "jobTitle": "Engineering Artisan - Electrician - Shift",
      "publishedDate": "Published 24 November 2023",
      "expiryDate": "Closing Date: 01 December 2023",
      "location": "Phola, Mpumalanga",
      "details": [
        "\n        <h1>Job Details</h1>\n    ",
        "\n        <div class=\"col-md-6\">\n            <div class=\"col-md-6\">\n\n\n\n\n                <div class=\"row padding-bottom-10\">\n                    <label class=\"job-detail-bold-header\" for=\"MinimumExperience\">Minimum experience</label>\n                    <span><label for=\"Associate\">Associate</label></span>\n                </div>\n                <div class=\"row padding-bottom-10\">\n                    <label class=\"job-detail-bold-header\" for=\"CompanyPrimaryIndustry\">Company primary industry</label>\n                    <span></span><label for=\"Mining_and_Metals\">Mining and Metals</label>\n                </div>\n                <div class=\"row padding-bottom-10\">\n                    <label class=\"job-detail-bold-header\" for=\"FunctionalAreaName\">Job functional area</label>\n                    <span><label for=\"Mining\">Mining</label></span>\n                </div>\n\n            </div>\n            <div class=\"col-md-6\">\n                                                            </div>\n        </div>\n\n\n    ",
        "\n        <div class=\"heading-blue\">\n            <h1>Job Description</h1>\n        </div>\n        <div class=\"vacancy-description\"><strong>Introduction</strong> <br><br>This position will be based at the Phola Plant close to Ogies in Mpumalanga.<br><br><strong>Description<br></strong> <br>The purpose of this position is to be responsible to assist in the smooth running of the respective plant sections whilst maintaining the specified client targets and adhering to health and safety standards.<br><br><strong>Duties and Responsibilities</strong> <br><ul><li>Investigate, diagnose and perform trade related maintenance and repair of equipment and machinery according to the maintenance requirements, standards and specifications.</li><li>Perform daily inspections in accordance with the Mine Health and Safety Act regulations, operational and company standards to report all defects and breakdowns on equipment and machinery to the Supervisor.</li><li>Develop, modify, construct and install all types of trade related equipment required for the safe operation of all engineering equipment.</li><li>Ensure that all installations and equipment are safe and in good working order after task completion.</li><li>Continuously monitor equipment failure and efficiency to improve trade specific equipment and systems.</li><li>Consult with production teams on maintenance activities that affects production.</li><li>Supports the achievement of engineering availability and production performance levels.</li><li>Ensure that maintenance related information is recorded and reported to the relevant planning office to support the maintenance of the planned / asset maintenance system</li></ul><strong>Qualification Requirements</strong> <br><ul><li>Grade 12 or equivalent qualification</li><li>Valid section 13 Trade test / Section 26(D) certificate</li><li>Valid driver’s license code B, EB or C1</li><li>Own transport to attend to call outs</li></ul><strong>Experience and Skills&nbsp;Requirements</strong> <br><ul><li>Minimum of 2-3 years’ experience as a qualified Electrician in a mineral processing plant</li><li>Valid MV MQA Certification</li><li>VSD and Soft Starter experience</li><li>English language proficiency</li><li>Time management skills</li></ul><br><br><br><br><br></div>\n            <div class=\"vacancy-apply-btn margin-bob-30\">\n<a class=\"btn btn-primary\" href=\"https://minopex.simplify.hr/Vacancy/Apply/c5mwi2\" rel=\"nofollow\">Apply</a>            </div>\n    "
      ],
      "apply": "https://minopex.simplify.hr/Vacancy/Apply/c5mwi2",
      "iconLink": "agency_icons/minopex.png"
    },
    {
      "jobTitle": "Instrument Mechanician",
      "publishedDate": "Published 24 November 2023",
      "expiryDate": "Closing Date: 01 December 2023",
      "location": "Phola, Mpumalanga",
      "details": [
        "\n        <h1>Job Details</h1>\n    ",
        "\n        <div class=\"col-md-6\">\n            <div class=\"col-md-6\">\n\n\n\n\n                <div class=\"row padding-bottom-10\">\n                    <label class=\"job-detail-bold-header\" for=\"MinimumExperience\">Minimum experience</label>\n                    <span><label for=\"Associate\">Associate</label></span>\n                </div>\n                <div class=\"row padding-bottom-10\">\n                    <label class=\"job-detail-bold-header\" for=\"CompanyPrimaryIndustry\">Company primary industry</label>\n                    <span></span><label for=\"Mining_and_Metals\">Mining and Metals</label>\n                </div>\n                <div class=\"row padding-bottom-10\">\n                    <label class=\"job-detail-bold-header\" for=\"FunctionalAreaName\">Job functional area</label>\n                    <span><label for=\"Mining\">Mining</label></span>\n                </div>\n\n            </div>\n            <div class=\"col-md-6\">\n                                                            </div>\n        </div>\n\n\n    ",
        "\n        <div class=\"heading-blue\">\n            <h1>Job Description</h1>\n        </div>\n        <div class=\"vacancy-description\"><strong>Introduction</strong><br><br>The position will be based at the Phola Plant close to Ogies in Mpumalanga.<br><br><strong>Description</strong><br><br>The purpose of this position is to maintain plant systems and equipment according to instrumentation and technical requirements.<br><br><strong>Duties &amp; Responsibilities:</strong><br><ul><li>Investigate, diagnose and perform trade related maintenance and repair of equipment and machinery according to the maintenance requirements, standards and specifications.</li><li>Perform daily inspections in accordance with the Mine Health and Safety Act regulations, operational and company standards to report all defects and breakdowns on equipment and machinery to the Supervisor.</li><li>Develop, modify, construct and install all types of trade related equipment required for the safe operation of all engineering equipment.</li><li>Ensure that all installations and equipment are safe and in good working order after task completion. · Continuously monitor equipment failure and efficiency to improve trade specific equipment and systems.</li><li>Consult with production teams on maintenance activities that affects production.</li><li>Supports the achievement of engineering availability and production performance levels.</li><li>Ensure that maintenance related information is recorded and reported to the relevant planning office to support the maintenance of the planned/asset maintenance system</li></ul><br><strong>Qualification Requirements:</strong><br><ul><li>Grade 12 or equivalent qualification</li><li>Valid section 13 Trade test / Section 26(D) certificate</li><li>Valid driver’s license code B, EB or C1 · Own transport to attend to call outs<br></li></ul><strong>Experience &amp; Skills Requirements:</strong><br><ul><li>Minimum of 2-3 years’ experience as a qualified Instrument Mechanician</li><li>English Language Proficiency</li><li>Time management skills</li></ul></div>\n            <div class=\"vacancy-apply-btn margin-bob-30\">\n<a class=\"btn btn-primary\" href=\"https://minopex.simplify.hr/Vacancy/Apply/cl5dbz\" rel=\"nofollow\">Apply</a>            </div>\n    "
      ],
      "apply": "https://minopex.simplify.hr/Vacancy/Apply/cl5dbz",
      "iconLink": "agency_icons/minopex.png"
    },
    {
      "jobTitle": "Process Operator - Plant",
      "publishedDate": "Published 01 December 2023",
      "expiryDate": "Closing Date: 08 December 2023",
      "location": "Postmasburg, Northern Cape",
      "details": [
        "\n        <h1>Job Details</h1>\n    ",
        "\n        <div class=\"col-md-6\">\n            <div class=\"col-md-6\">\n\n\n\n\n                <div class=\"row padding-bottom-10\">\n                    <label class=\"job-detail-bold-header\" for=\"MinimumExperience\">Minimum experience</label>\n                    <span><label for=\"Entry_Level\">Entry Level</label></span>\n                </div>\n                <div class=\"row padding-bottom-10\">\n                    <label class=\"job-detail-bold-header\" for=\"CompanyPrimaryIndustry\">Company primary industry</label>\n                    <span></span><label for=\"Mining_and_Metals\">Mining and Metals</label>\n                </div>\n                <div class=\"row padding-bottom-10\">\n                    <label class=\"job-detail-bold-header\" for=\"FunctionalAreaName\">Job functional area</label>\n                    <span><label for=\"Mining\">Mining</label></span>\n                </div>\n\n            </div>\n            <div class=\"col-md-6\">\n                                                            </div>\n        </div>\n\n\n    ",
        "\n        <div class=\"heading-blue\">\n            <h1>Job Description</h1>\n        </div>\n        <div class=\"vacancy-description\"><strong>Introduction</strong> <br><br>This position will be based at a site in Postmasburg in the Northern Cape.<br><br><strong>Description</strong> <br><br>The purpose of this position is to assist in the smooth running of the respective plant sections whilst maintaining the specified client targets and adhering to Health and Safety standards<br><br><strong>Duties and Responsibilities</strong><br><ul><li>Continuously monitor plant equipment and report to the Control / Shift Supervisor </li><li>Ensure adherence to the specified process parameters within the respective sections</li><li>Maintain a high standard of housekeeping</li><li>Support the achievement of production performance levels</li><li>Perform basic maintenance activities to assist maintenance staff and replace screens, idlers etc. where engineering is not required</li><li>Maintain Plant parameters to achieve KPI’s</li></ul><strong>Qualification Requirements</strong><br><ul><li>Grade 12 </li><li>National Certificate Mineral Processing Level 2 or an equivalent Minerals Processing Qualification will be advantageous</li></ul><strong>Experience and Skills&nbsp;Requirements</strong> <br><ul><li>Minimum 1 to 2 years’ experience as a Process Attendant</li><li>Production Plant experience is essential</li><li>English language proficiency</li><li>Time management skills</li></ul><br><br><br><br><br></div>\n            <div class=\"vacancy-apply-btn margin-bob-30\">\n<a class=\"btn btn-primary\" href=\"https://minopex.simplify.hr/Vacancy/Apply/ahu9nm\" rel=\"nofollow\">Apply</a>            </div>\n    "
      ],
      "apply": "https://minopex.simplify.hr/Vacancy/Apply/ahu9nm",
      "iconLink": "agency_icons/minopex.png"
    }
  ]
}
